[package]
name = "pillow_simd_ffi"
version = "0.0.1"
authors = ["Peter Jin <peterhaijin@gmail.com>"]

[lib]
name = "pillow_simd_ffi"
path = "src/lib.rs"

[build-dependencies]
bindgen = "*"
gcc = "*"
walkdir = "*"

[dependencies]
lazy_static = "*"
